### ISSUE TITLE
Rename to Bridget

### ISSUE THREAD

**Issue by alexanderedge** [guardian/bridget#20]
Since the competition has finished, I think we should rename this repo and its packages to `Bridget` as soon as possible and update all documentation.

**Comment by alexanderedge** [comment]
Also don't forget the GitHub Actions!

**Comment by alexanderedge** [comment]
The iOS package repo is now https://github.com/guardian/bridget-swift

**Comment by alexanderedge** [comment]
PR for updating the GitHub action for updating the iOS repo: https://github.com/guardian/mobile-apps-thrift/pull/21

**Comment by alexduf** [comment]
I've renamed the repo to Bridget. Couldn't resist :)

**Comment by alexanderedge** [comment]
Reopened as renaming this repo will have knock-on effects for consumers of it. There are some files in here that need to be updated.
