### ISSUE TITLE
Ability to lock screen (disable swipe from webView)

### ISSUE THREAD

**Issue by webb04** [guardian/bridget#22]
We've had two reports from people developing interactives saying it would be useful to have a locking feature.

This would disable side swiping between articles when set to `true` and enable it again when set to `false`

We have this feature on Android in the current templates, but it looks like a recent iOS release has broken some interactives with side scrolling. 

```
service Interactive {
       void lockScreen(1:bool shouldLock)
}
```

**Comment by JamieB-gu** [comment]
Couple of questions:

1. Will this cause a poor UX experience for people who are used to swiping sideways through the news @zeek01? Will they think the app is broken? Do we know how many people use this feature?
2. Should we call it something like `preventHorizontalSwipe`or `lockHorizontalSwipe`? `lockScreen` may cause confusion, as it could refer to the act of locking your device screen _or_ the lock screen itself.
