### ISSUE TITLE
Videos in apps-rendering

### ISSUE THREAD

**Issue by webb04** [guardian/bridget#34]
### Current app
- Media atoms are native videos using the YouTube SDK. They now support pinned video
- Video embeds are iframes in the webview

I think the YouTube SDK let's us control if we show ads or not, are there any other benefits of having this native?

If we want to continue this approach we could add the following APIs:

```
struct VideoSlot {
    1: required i32 x;
    2: required i32 y;
    3: optional i32 height;
    4: optional i32 width;
    5: required string videoId;
    5: required string posterUrl;
    5: required i32 duration;
}

service Videos {
    void insertVideos(1:list<VideoSlot> videoSlots),
    void updateVideos(1:list<VideoSlot> videoSlots)
}
```

Another approach would be to not add an api and do it in the webview (possibly pinning media atoms and video embeds). But we may lose the ability to control adverts.

**Comment by maxspencer** [comment]
I think this approach (of having native YT videos like native ads) sounds sensible. The key benefits are (1) not showing ads to native users (2) ability to pin videos, including across screens and other apps (potentially) and (3) better ability to integrate with native media APIs.

**Comment by JamieB-gu** [comment]
To clarify, are you suggesting treating non-atom video embeds the same as video atoms?

**Comment by maxspencer** [comment]
> To clarify, are you suggesting treating non-atom video embeds the same as video atoms?

If we could treat all videos in articles the same way that would be great.

**Comment by JamieB-gu** [comment]
Is there any reason, apart from legacy, that not all video embeds are video atoms? @akash1810

**Comment by akash1810** [comment]
> Is there any reason, apart from legacy, that not all video embeds are video atoms? @akash1810

Nope, just legacy. We've identified that it would be beneficial to migrate, however it isn't prioritised.
