### ISSUE TITLE
Add human-readable names for Topics

### ISSUE THREAD

**Issue by maxspencer** [guardian/bridget#37]
The `Topic` model we're using for the `Notifications` service only comes with a topic `id`. This means that in the native app's notifications settings window the topics currently show up like this under "Other alerts":

![Screenshot_20200514-134401](https://user-images.githubusercontent.com/951849/81935798-19251280-95e9-11ea-904e-945128acd290.png)

This isn't the end of the world, but it would be nice to make them appear as they do now with a prettier name and under the correct "Contributors" heading.

![Screenshot_20200514-134144](https://user-images.githubusercontent.com/951849/81935763-10344100-95e9-11ea-820c-84a0bc5eb750.png)

Looking at how topics are [currently represented in MAPI](https://mobile.guardianapis.com/uk/items/world/2020/may/14/coronavirus-latest-at-a-glance-may-14) we see there's basically the equivalent of `Topic.id` plus a `displayName` and `type`:

```json
topics": [
    {
        "displayName": "Simon Burnton",
        "topic": {
            "type": "tag-contributor",
            "name": "profile/simonburnton"
        }
    }
]
```

**Comment by webb04** [comment]
I think this is nicer for users 👍I'm sure we can get less clear names than `profile/simonburnton` too
