### ISSUE TITLE
Provide additional parameters for ads

### ISSUE THREAD

**Issue by maxspencer** [guardian/bridget#38]
I've dug around in the Android native code and have found some  parameters that we use for loading MPU ads which I propose we start passing via Bridget.

As I can tell, this is the set of values we use when making ad requests currently:

```kotlin
item.metadata.adTargetingPath,
getKeywordsAsString(item.metadata),
AdHelper.getSeriesName(item),
item.style.colourPalette,
item.links.webUri,
item.metadata.adServerParams,
index,
pageId,
```

From: https://github.com/guardian/android-news-app/blob/0edcd954ca850ff0c45d72fd1a221064230e5484/android-news-app/src/main/java/com/guardian/feature/stream/cards/ArticleAdvertCardView.kt#L48-L55

It looks like the `item.metadata.adServerParams` that MAPI already provides could replace a lot of the other values which we compute client-side - I will separately investigate refactoring our code to remove any of these that are unnecessary.

Could we pass a similar `Map` of key value pairs for each ad via Bridget?

**Comment by webb04** [comment]
Yeah It looks like some of that is duplicated as I think series, keywords and url (the id anyway) are in `adServerParams`.

**Comment by alexduf** [comment]
For what it's worth `item.metadata.adServerParams` is deprecated in favour of `item.metadata.commercial.adTargeting`
