### ISSUE TITLE
Provide title for galleries

### ISSUE THREAD

**Issue by maxspencer** [guardian/bridget#40]
For 100% compatibility with the existing article gallery screen we'd need to pass the article title via the `launchSlideshow` bridget call:

https://github.com/guardian/bridget/blob/62eed9944e6ea614a30da6dfd51746ab01bcb489/thrift/native.thrift#L56-L58

This would appear where the "TODO" is in the top-left corner below:

![Screenshot_1590593600](https://user-images.githubusercontent.com/951849/83040992-de36cc00-a037-11ea-9f37-fb484c039a28.png)

**Comment by webb04** [comment]
Released in Bridget `0.55.0`
https://github.com/guardian/bridget/pull/41
