### ISSUE TITLE
API to set background and navbar button colours

### ISSUE THREAD

**Issue by webb04** [guardian/bridget#47]
Should we set the webview background colour and top navbar button colours through Bridget?

![IMG_5386](https://user-images.githubusercontent.com/11618797/84132152-6c9a4d00-aa3d-11ea-9423-9b72623f976d.PNG)

**Comment by alexduf** [comment]
We might have a bit of a flickering effect if we do that so I'm not sure it's a good idea :/

**Comment by webb04** [comment]
True, maybe they could be animated but that would be more work. I don't think this is high priority though so maybe it's something we think about later.

It could be nice for interactives to customise the theme a bit more.

**Comment by georgeblahblah** [comment]
This is an interesting idea but possibly stale by now!
